// src/nav/navConfig.js
export const NAV_ITEMS = [
  {
    key: "dashboard",
    label: "Admin-Dashboard",
    path: "/admindashboard",
    icon: "🏠",
    requireAll: ["CanViewAdminDashboard"],
  },
  {
    key: "mybookings",
    label: "การจองของฉัน",
    path: "/mybookings",
    icon: "📝",
    requireAll: ["CanReservation"],
  },
  {
    key: "emp",
    label: "จัดการพนักงาน",
    path: "/employees",
    icon: "🧑‍💼",
    requireAll: ["CanManageEmployee"],
  },
  // {
  //   key: "drv",
  //   label: "จัดการคนขับ",
  //   // path: "/drivers",
  //   icon: "🚖",
  //   requireAll: ["CanManageDriver"],
  // },
  {
    key: "position",
    label: "จัดการตำแหน่ง",
    path: "/position-manage",
    icon: "🗺️",
    requireAll: ["CanManagePositionPermissions"],
  },
  {
    key: "posper",
    label: "จัดการสิทธ์ของตำแหน่ง",
    path: "/position-permission-manage",
    icon: "🗺️",
    requireAll: ["CanManagePositionPermissions"],
  },
  // {
  //   key: "routes",
  //   label: "จัดการเส้นทาง",
  //   // path: "/routes",
  //   icon: "🗺️",
  //   requireAny: ["CanManageRoutes", "CanViewReports"],
  // },
  {
    key: "report",
    label: "รายงาน",
    path: "/reports",
    icon: "📊",
    requireAll: ["CanViewReports"],
  },
  // {
  //   key: "perms",
  //   label: "สิทธิ์การใช้งาน",
  //   path: "/permissions",
  //   icon: "🔐",
  //   requireAll: ["CanManagePermissions"],
  // },
  {
    key: "booking",
    label: "การจอง",
    path: "/bookings",
    icon: "📝",
    requireAll: ["CanReservation"],
  },
  {
    key: "driverdash",
    label: "ตารางงาน",
    path: "/driver-dashboard",
    icon: "📝",
    requireAll: ["DriverPermission"],
  },

  // {
  //   key: "booking",
  //   label: "การจอง",
  //   path: "/bookings",
  //   icon: "📝",
  //   requireAll: ["CanReservation"],
  // },
];
